export const churchInfo = {
  showGiving: false,
  name: "Peace Baptist Church",
  shortName: "Peace Baptist",
  tagline: "Wilmington, NC · Est. 1975",
  address: {
    street: "320 Military Cutoff Rd",
    city: "Wilmington",
    state: "NC",
    zip: "28405",
    full: "320 Military Cutoff Rd, Wilmington, NC 28405",
  },
  phone: "(910) 791-4034",
  phoneTel: "+19107914034",
  email: "peacebible@bellsouth.net",
  pastor: "Pastor Rudy Shepard",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=320+Military+Cutoff+Rd+Wilmington+NC+28405",
  social: {
    facebook: "https://www.facebook.com/p/Peace-Baptist-Church-100068974954914/",
    youtube: "https://www.youtube.com/peacebaptistchurch",
    instagram: null,
  },
  serviceTimes: [
    { label: "Sunday School", time: "9:30 AM" },
    { label: "Sunday Morning Worship", time: "10:30 AM" },
    { label: "Sunday Evening Service", time: "6:00 PM" },
    { label: "Wednesday Bible Study", time: "7:00 PM" },
  ],
  scripture: {
    reference: "Hebrews 10:25",
    text: "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching.",
  },
  images: {
    hero: "/images/hero-sanctuary.jpg",
    welcome: "/images/church-exterior.jpg",
    aboutHero: "/images/church-exterior.jpg",
    aboutBuilding: "/images/church-building.jpg",
    aboutSanctuary: "/images/hero-sanctuary.jpg",
    churchSign: "/images/church-sign.jpg",
    worship: "/images/hero-sanctuary.jpg",
    nursery: "/images/nursery.jpg",
    pastor: "https://media.base44.com/images/public/6a41a8ed40c77c0dcdea5394/f4b111e89_Rudy-Shepard.webp",
  },
};