export const churchInfo = {
  showGiving: false,
  name: "Peace Baptist Church",
  shortName: "Peace Baptist",
  tagline: "Wilmington, NC · Est. 1975",
  address: {
    street: "320 Military Cutoff Rd",
    city: "Wilmington",
    state: "NC",
    zip: "28405",
    full: "320 Military Cutoff Rd, Wilmington, NC 28405",
  },
  phone: "(910) 791-4034",
  phoneTel: "+19107914034",
  email: "peacebible@bellsouth.net",
  pastor: "Pastor Rudy Shepard",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=320+Military+Cutoff+Rd+Wilmington+NC+28405",
  social: {
    facebook: "https://www.facebook.com/p/Peace-Baptist-Church-100068974954914/",
    youtube: "https://www.youtube.com/@PeaceBaptistChurch1975",
    instagram: null,
  },
  serviceTimes: [
    { label: "Sunday School", time: "9:30 AM" },
    { label: "Sunday Morning Worship", time: "10:30 AM" },
    { label: "Sunday Evening Service", time: "6:00 PM" },
    { label: "Wednesday Bible Study", time: "7:00 PM" },
  ],
  scripture: {
    reference: "Hebrews 10:25",
    text: "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching.",
  },
  liveStream: {
    provider: "simple-streamz",
    channelId: "ef5d376560a945d2ba92",
    embedBase: "https://simplestreamz.io",
  },
  pastServicesPlaylist: {
    embedUrl: "https://www.youtube.com/embed/videoseries?list=PLVNXaOHxtsylMo4TqKj2rN-ZI3luGg_x3",
    url: "https://www.youtube.com/playlist?list=PLVNXaOHxtsylMo4TqKj2rN-ZI3luGg_x3",
  },
  bibleBelieversBroadcast: {
    title: "Bible Believers Broadcast",
    embedUrl: "https://hearthis.at/set/521575/embed/",
    pageUrl: "https://hearthis.at/set/521575/",
  },
  googleMapsEmbed:
    "https://maps.google.com/maps?q=320+Military+Cutoff+Rd,+Wilmington,+NC+28405&hl=en&z=14&output=embed",
  ministries: [
    {
      id: "sunday-school",
      name: "Sunday School",
      description:
        "Bible-centered classes for all ages before morning worship. A great way to grow in Scripture and fellowship.",
      leader: "Church Staff",
      meeting_time: "Sundays at 9:30 AM",
      image_url: "/images/hero-sanctuary.jpg",
      status: "active",
    },
    {
      id: "youth",
      name: "Youth Ministry",
      description:
        "Teaching and activities for young people to grow in faith, build friendships, and serve the Lord.",
      leader: "Youth Leaders",
      meeting_time: "Sunday & Wednesday",
      image_url: "/images/youth-ministry.jpg",
      status: "active",
    },
    {
      id: "nursery",
      name: "Nursery",
      description:
        "A safe, caring environment for infants and toddlers during worship services.",
      leader: "Nursery Volunteers",
      meeting_time: "During all services",
      image_url: "/images/nursery.jpg",
      status: "active",
    },
    {
      id: "outreach",
      name: "Soul Winning & Outreach",
      description:
        "Door-to-door visitation, community outreach, and sharing the Gospel throughout Wilmington.",
      leader: "Pastor Rudy Shepard",
      meeting_time: "Ongoing",
      image_url: "/images/church-exterior.jpg",
      status: "active",
    },
    {
      id: "bus",
      name: "Bus Ministry",
      description: "Transportation ministry helping families attend church services.",
      leader: "Bus Captain",
      meeting_time: "Sundays",
      image_url: "/images/church-building.jpg",
      status: "active",
    },
  ],
  images: {
    notificationIcon: "/images/church-exterior.jpg",
    splash: "/images/church-exterior.jpg",
    hero: "/images/hero-sanctuary.jpg",
    welcome: "/images/church-exterior.jpg",
    aboutHero: "/images/church-exterior.jpg",
    aboutBuilding: "/images/church-building.jpg",
    aboutSanctuary: "/images/hero-sanctuary.jpg",
    churchSign: "/images/church-sign.jpg",
    worship: "/images/hero-sanctuary.jpg",
    nursery: "/images/nursery.jpg",
    pastor: "https://media.base44.com/images/public/6a41a8ed40c77c0dcdea5394/f4b111e89_Rudy-Shepard.webp",
  },
};